subject = "Название предмета"
description = "Материалы для подготовки к зачёту/экзамену"
term = 4 # номер семестра
authors = [
  "Егор Смирнов",
  "Артём Рудяк",
  "Артём Соловьёв",
  "Александр Храмов",
  "Роберт Толстов",
  "Данила Григорьев",
  "Михаил Чертков",
  "Виктория Лазарева",
  "Вадим Карасёв",
  "Артём Кудяков",
  "Радомир Тюменцев",
  "Александр Железко",
  "Иван Архипов",
  "Михаил Леонтьев",
  "Маргарита Потапкина",
]

[sections]
numbering = true
prefix = "Вопрос"
sections = [
  # "Множества. Операции над множествами. Характеристический вектор множества. Теорема о характеристических векторах множеств. Теорема о числе подмножеств $n$-элементного множества",
  # "Декартово произведение множеств. Бинарные отношения. Операции над бинарными отношениями. Способы задания бинарных отношений. Теорема о матрицах бинарных отношений",
  # "Срезы бинарного отношения, первая и вторая проекции бинарного отношения, $1$-и $2$-полные отношения, взаимно-однозначные отношения, отображения, инъекции, сюрьекции и биекции. Утверждение о биекции",
  # "Типы бинарных отношений",
  # "Эквивалентности. Разбиение множества. Классы эквивалентности, фактор-множество. Основная теорема об эквивалентностях",
  # "Отношения порядка, упорядоченное множество, линейно упорядоченное множество, убывающая цепь, длина цепи, высота элемента, наибольший и наименьший элементы, диаграмма упорядоченного множества",
  # "Конечный детерминированный автомат, способы задания автомата. Расширенные функции переходов и выходов. Сравнимые автоматы. Изоморфизм автоматов. Теорема о изоморфизме автоматов",
  # "Отношения неразличимости и $k$-неразличимости состояний автомата. Эквивалентные автоматы. Минимальный автомат. Исключительный класс автоматов",
  # "Отношение достижимости и взаимной достижимости состояний автомата. Признак  эквивалентности  сравнимых сильно связных автоматов",
  # "Фактор-автомат автомата. Теорема о  фактор-автомате",
  # "Теорема о минимальных автоматах. Теорема о минимальном автомате",
  # "Метод построения минимального автомата",
  # "Лемма о числе классов в $epsilon_k$. Лемма о числе состояний в классах $epsilon_k$. Теорема о $(n - r + 1)$ различимых состояниях. Теорема Мура",
  # "Понятие эксперимента с автоматом. Характеристика  экспериментов с автоматами. Диагностическая и установочные задачи",
  # "$p$-преемник состояния, $sigma$-множество, простое, однородное и кратное $sigma$-множество. $А$-группа, простая и однородная $А$-группа, $p$-преемник $А$-группы",
  # "Дерево преемников",
  # "Диагностическое дерево. Диагностический путь, диагностическая последовательность. Минимальная диагностическая последовательность",
  # "Лемма о диагностической последовательности. Теорема о минимальных диагностических последовательностях",
  # "Простой кратчайший безусловный диагностический эксперимент. Разделение диагностической последовательноси на подпоследовательнсти. Простой условный диагностический эксперимент. Теорема оценка порядка условного диагностического эксперимента",
  # "Установочное дерево. Установочный путь, установочная последовательность. Минимальная установочная последовательность",
  # "Лемма об  установочной последовательности. Теорема о минимальных установочных последовательностях",
  # "Алгоритм кратчайшего простого безусловного установочного эксперимента. Разделение установочной последовательноси на подпоследовательнсти. Простой условный установочный эксперимент",
  # "Регулярные  эксперименты. Регулярная установочная последовательность. Алгоритм построения регулярной установочной последовательности",
  # "Теорема о длине безусловного установочного эксперимента. Следствие",
  # "Регулярный условный установочный эксперимент. Теорема о порядке условного установочного эксперимента",
  # "Задача распознавания автоматов. Теорема  о необходимом и достаточном условии распознавания автомата из заданного класса",
  # "Теорема оценка длины простого безусловного эксперимента  для распознавания автомата из заданного класса. Следствие",
  # "Регулярный условный установочный эксперимент для распознавания автомата из заданного класса",
  # "Детерминированные функции. Занумерованное дерево. Вес детерминированной функции",
  # "О-д. функции, диаграмма Мура, система канонических уравнений автомата (о.д. функции). Теорема об о.д. функциях и автоматных функциях",
  # "Структурный автомат, система канонических уравнений структурного автомата (о.д. функции)",
  # "Операция суперпозиции. Теорема о суперпозиции детерминированных функций (о замкнутости класса д. функций относительно суперпозиции)",
  # "Функции, зависящие от переменной с запаздыванием. Операция обратной связи",
  # "Теорема о замкнутости класса о.д. функций относительно операции обратной связи. Теорема о полноте системы ${f not, f^(and), f^(or), arrow(x)}$.  Теорема об алгоритмической неразрешимости проблемы полноты в классе о-д. функций",
]
